name: Dispatch Build

on:
  workflow_call:

env:
  CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  SIGNING_KEY: ${{ secrets.PGP_SECRET }}
  SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  upload_demos_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.12.1
#        with:
#          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

#      - name: Build everything
#        run: |
#          ./gradlew build

      - name: Build web Samples
        run: |
          ./gradlew :examples:samples:teavm:jolt_samples_build

      - name: Upload Samples app demo to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/samples/teavm/build/dist/webapp
          destination_dir: ./examples/samples